plugins {
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = '1.0'
group = 'com.redcraft86.workspace'

subprojects {
    apply plugin: 'java'

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    java.toolchain.languageVersion = JavaLanguageVersion.of(21)

    idea {
        module {
            downloadSources = true
            downloadJavadoc = true
        }
    }

    configurations {
        runtimeClasspath.extendsFrom localRuntime
    }

    repositories {
        mavenCentral()
        mavenLocal()

        maven { url = "https://maven.neoforged.net/releases" }

        maven { url = "https://maven.wispforest.io/releases/" }
        maven { url = "https://maven.su5ed.dev/releases" }

        maven { url = "https://api.modrinth.com/maven" }
        maven { url = "https://www.cursemaven.com" }

        maven { url = "https://jitpack.io" }
    }

    dependencies {
        // Shared QOL mods
        localRuntime "maven.modrinth:better-modlist:1.1.22-neoforge"
        localRuntime "maven.modrinth:emi:1.1.24+1.21.1+neoforge"
        localRuntime "maven.modrinth:cucumber:8.0.16-neoforge"
        localRuntime "maven.modrinth:jade:15.10.5+neoforge"

        localRuntime "maven.modrinth:ferrite-core:7.0.3-neoforge"
        localRuntime "maven.modrinth:c2me-neoforge:0.3.0+alpha.0.93+1.21.1"
        localRuntime "maven.modrinth:lithium:mc1.21.1-0.15.3-neoforge"
        localRuntime "maven.modrinth:sodium:mc1.21.1-0.6.13-neoforge"
        localRuntime "maven.modrinth:sodium-extra:mc1.21.1-0.6.0+neoforge"
        localRuntime "maven.modrinth:reeses-sodium-options:mc1.21.4-1.8.3+neoforge"
    }
}
