plugins {
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = '1.0'
group = 'com.mcmodding.workspace'

subprojects {
    apply plugin: 'java'

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    java.toolchain.languageVersion = JavaLanguageVersion.of(21)

    idea {
        module {
            downloadSources = true
            downloadJavadoc = true
        }
    }

    configurations {
        runtimeClasspath.extendsFrom localRuntime
    }

    repositories {
        mavenCentral()
        mavenLocal()

        /**
         * Add your shared/common maven URLs here
         */
        maven { url = 'https://www.cursemaven.com' }
        maven { url = 'https://api.modrinth.com/maven' }
        maven { url = 'https://maven.neoforged.net/releases' }
    }

    dependencies {
        /**
         * Add your shared/common runtime mods here
         * While you can add actual dependencies here it is recommended that you keep those restricted per mod
         * The purpose of this is to load additional third party mods for when you play test your own mods
         * For instance, I always run these alongside testing my own mods:
         *      Catalogue - Nice and clean mod menu screen
         *      Configured - Nice and clean mod config screen
         *      Cucumber - Showing item Tags and NBT/DataComponents while holding down keys
         *      EMI - JEI just didn't work for me for some reason
         */
        localRuntime 'curse.maven:catalogue-459701:6926815'
        localRuntime 'curse.maven:configured-457570:7276577'
        localRuntime 'curse.maven:cucumber-272335:7180790'
        localRuntime 'curse.maven:emi-580555:6420931'
    }
}
