# Memory Settings
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Settings
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neoforge_version=21.1.217
neoforge_version_range=[21.1.217,)
loader_version_range=[1,)
mappings_version=2024.11.17
