/////////////////////////
// Add more mods here! //
/////////////////////////
dependencies {
    implementation project(":SampleLib")
    implementation project(":SampleMod")
}


version = "1.0"
group = "com.mcmodding.${mod_id}"
jar.archiveFileName = "${mod_id}-${minecraft_version}-1.0.jar"
base.archivesName = mod_id

neoForge {
    version = neoforge_version

    parchment {
        mappingsVersion = parchment_version
        minecraftVersion = minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            neoforge_version            : neoforge_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id
    ]

    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata