modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
    version="1.0"
    modId="modrunner"
    displayName="Mod Runner"
    description='''Simple utility mod to run all mods in this workspace'''
    authors="None"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
