## Dependencies
samplelib_version=1.0.0

## Mod Properties
mod_id=samplemod
mod_name=Sample Mod
repo_name=SampleMod
mod_license=MIT
mod_version=1.0.0
mod_authors=NoAuthor
mod_group_id=com.samples.samplemod
mod_description=A sample mod for multi-workspace setup. Requires SimpleLib v1.0.0
mod_credits=NoCredits