modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
    modId="${mod_id}"
    displayName="Mod Runner"
    description='''Simple utility mod to run all mods in this workspace'''
    authors="NoAuthor"
    version="1.0"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"